### ISSUE TITLE
create a volume from snapshot faild with error.

### ISSUE THREAD

**Issue by pootow** [yintai/playback#7]
Volume Overview
Info

Name
    snapshot-4-to-vol
ID
    65db3ffc-ec1b-4899-9717-73cd3edd9219
Description
    from snapshot
Status
    Error

**Comment by pootow** [comment]
Maybe it's just not enough volume space. I've create a 2G volume with success.
I'll try again to confirm.

**Comment by pootow** [comment]
I confirm that is not a issue, just no enough volume space.

**Comment by jiasir** [comment]
@pootow Thanks your reporting.
